### ISSUE TITLE
Lua for swift

### ISSUE THREAD

**Issue by lilliesAndRoses** [narfdotpl/lua-on-ios#1]
Hello,
This is a great pod. Do you have a similar infrastructure for swift?

**Comment by narfdotpl** [comment]
No, I didn't touch Lua since creating this repo ~3 years ago. If I were to extend a Swift app with scripting, I would take a longer look at [JavaScriptCore](http://nshipster.com/javascriptcore/) because it is supported by the first party (Apple).
